---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: animegan-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animegan-pod

  template:
    metadata:
      labels:
        app: animegan-pod
    spec:
      containers:
        - name: animegan-pod
          image: rahools/animegan # to fill
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: animegan-service
spec:
  selector:
    app: animegan-pod
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 80
  type: LoadBalancer